# Generated by Django 4.1.3 on 2023-09-29 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('image', models.URLField()),
                ('price', models.FloatField()),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=80, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('url', models.URLField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DemandePret',
            fields=[
                ('id_demande_pret', models.AutoField(primary_key=True, serialize=False)),
                ('date_debut', models.DateField(null=True)),
                ('h_debut', models.TimeField(null=True)),
                ('date_fin', models.DateField(null=True)),
                ('h_fin', models.TimeField(null=True)),
                ('pj_demande', models.TextField(null=True)),
                ('acquereur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Artwork.profile')),
                ('artwork', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Artwork.artwork')),
            ],
            options={
                'verbose_name': 'Demande Pret',
                'verbose_name_plural': 'Demandes Prets',
            },
        ),
        migrations.AddField(
            model_name='artwork',
            name='proprietaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Artwork.profile'),
        ),
    ]
