# Generated by Django 4.1.3 on 2023-09-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandepret',
            name='pj_demande',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
